### PR TITLE
Stateful services should be preserved, even if they are the primary

### PR DESCRIPTION
**Pull request by davidgiesberg**
Addresses #35 

I don't think there are any repercussions, but I'm not sure if there is any nuance to this method's behavior that I'm missing.

### CODE REVIEW

**Comment by phopkins** [comment]
Interesting. We haven't given this use case much thought because our stateful services have typically been vendored things (like MySQL) and the services under development aren't.

This PR doesn't go far enough to what you'd want, though, since Galley will still remove the container in the finalizeContainer step.

I think if that were in place this could work, though I'd probably also want to add in warnings if the container wouldn't be configured correctly (for example, if it had lost a link due to the container it was linking to being recreated).

You may also want to consider having your database store its data in volume-mapped data container, which could be marked as stateful and for the most part not touched. You'd have more freedom then in changing your database's image or other options without losing dev data.

**Comment by davidgiesberg** [comment]
Good points - I'll chase down both of those threads.

**Comment by davidgiesberg** [comment]
Per my comments in #36, I don't think this work is necessary. Thanks for the insight @phopkins.

**Comment by phopkins** [comment]
SG! Thanks for the update.

**Pull request closed without merging**
