### PR TITLE
Add support for pulling private images from private Docker Hub-style registries

### PR DESCRIPTION
**Pull request by davidgiesberg**
Addresses #24 

This works for me and resolves the original problem I was seeing.

I updated `registry` in my `Galleyfile` to match the `~/.docker/config.json` auth block:

````
    registry: 'https://index.docker.io/v1/',
````

### CODE REVIEW

**Comment by phopkins** [comment]
Sweet. I think we have some stuff for a Galley release later today. Thanks so much!

**Comment by phopkins** [comment]
@davidgiesberg I'm looking this over and I actually think it's conflating 2 things. The `registry` in the Galleyfile is there to allow for implicitly naming images based on registry + "/" + service name. I think if you have stuff on the default dockerhub that you'd probably use your username or org name as the registry?

The "no dots, therefore use Docker's registry" is separate logic. The question then becomes what key to look up in the auth hash for the no-dots case.

As of now, I'm not against hard-coding Docker's URL in the Galley codebase, at least if Docker is consistent about using "https://index.docker.io/v1/". It may be desirable either now or later to parameterie that in the Galleyfile, but I think that should be done under a `dockerHubUrl` key or something different from `registry`.

Does that match your intention? I'm not very familiar with private DockerHub bits so I don't know if I'm thinking of `registry` right in that context.

**Comment by davidgiesberg** [comment]
@phopkins Yeah, looking at it fresh eyes this morning, I think there may be a terminology problem here. I think what you're referring to as a _registry_ is actually a _repository_ and I've managed to overload it at the same time.

I believe that the most verbose way to locate an image is with `registry/repository/name`. Registries can be hostnames or URLs. `~/.docker/config.json` appears to group the `auths` by what I'm referring to as registries (which makes sense to me). 

I think that the `registry` value in Galley should _actually_ be `repository`, which is typically a username or organization name.

I don't have a good understanding about the logic that the Docker client uses to pick which repository to pull from, but obviously I think it would be ideal to mirror whatever they're doing.

All of that said, I need to chew on it a bit to figure out what the ideal fix is here.

**Comment by phopkins** [comment]
We use it as "registry" internally because we have a private hub, so it's a server name for us.

**Comment by davidgiesberg** [comment]
Got it.

After some more tinkering, I think I can work around the problem I'm running into here since it sounds like my use case is a bit different from yours.

Here is an example of what my Galleyfile looks like:

````js
module.exports = {
  CONFIG: {
    registry: 'index.docker.io'
  },
  'app':{
    image: 'union/fooapp:0.1.9',
  }
}
````

My expectation was that Galley would pull the image from the registry specified above, but it looks like it only tries to do that if `image` is not specified, which won't work for my use case, since I'm trying to specify a particular tag.

_Separately_, `docker login` defaults to setting the server name `https://index.docker.io/v1`, which I _think_ galley should be able to grok and try to use. (I'm a bit fuzzier on this logic, since I haven't tinkered with that and compared to what the docker client's behavior is.

I think I can close this PR and avoid the problem altogether, by taking both of these steps:

1. `docker login index.docker.io`, so credentials with that key are available for Galley to find
2. Update the above Galleyfile to look like this:

````js
module.exports = {
  'app':{
    image: 'index.docker.io/union/fooapp:0.1.9',
  }
}
````

Thanks for joining me on this voyage anyhow @phopkins. :-)

**Comment by phopkins** [comment]
Ah, I see. Makes sense.

I think I'll still try to make the change that defaults to "https://index.docker.io/v1/" as the auth key when the image has no dots in it, since that matches Docker's behavior.

**Pull request closed without merging**
